# Run docker-compose build or docker-compose up to build/update the darkcastle image
FROM opensuse/tumbleweed

RUN zypper -n dup --no-recommends --auto-agree-with-licenses
RUN zypper -n in --no-recommends --allow-unsigned-rpm /hostdir/dc*rpm xz
WORKDIR /var/lib/dcastle/lib
RUN /usr/bin/testDC
CMD ["/usr/bin/dcastle", "-P"]

LABEL Name=darkcastle-prod Version=0.0.5
