#include "DC/Command.h"
#include "DC/character.h"
#include "DC/common.h"

QMap<QString, Command> Commands::map_ = {};

// The last integer will affect a char being removed from hide when they perform the command.
// 0  - char will always become visibile.
// 1  - char will not become visible when using this command.
// 2+ - char has a greater chance of breaking hide as this increases.
const QList<Command> Commands::commands_ =
    {
        // Movement commands
        {"north", do_move, position_t::STANDING, 0, CMD_NORTH, true, 1, CommandType::all},
        {"east", do_move, position_t::STANDING, 0, CMD_EAST, true, 1, CommandType::all},
        {"south", do_move, position_t::STANDING, 0, CMD_SOUTH, true, 1, CommandType::all},
        {"west", do_move, position_t::STANDING, 0, CMD_WEST, true, 1, CommandType::all},
        {"up", do_move, position_t::STANDING, 0, CMD_UP, true, 1, CommandType::all},
        {"down", do_move, position_t::STANDING, 0, CMD_DOWN, true, 1, CommandType::all},

        // Common commands
        {"newbie", do_newbie, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"cast", do_cast, position_t::SITTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"filter", do_cast, position_t::SITTING, 0, CMD_FILTER, 0, 0, CommandType::all},
        {"sing", do_sing, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"exits", do_exits, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"f", do_fire, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 25, CommandType::all},
        {"get", do_get, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"inventory", do_inventory, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"k", do_kill, position_t::FIGHTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"ki", do_ki, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"kill", do_kill, position_t::FIGHTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"look", do_look, position_t::RESTING, 0, CMD_LOOK, true, 1, CommandType::all},
        {"loot", do_get, position_t::RESTING, 0, CMD_LOOT, 0, 0, CommandType::all},
        {"glance", do_look, position_t::RESTING, 0, CMD_GLANCE, true, 1, CommandType::all},
        {"order", do_order, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"rest", do_rest, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"recite", do_recite, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"recall", &Character::do_recall, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"score", do_score, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"scan", do_scan, position_t::RESTING, 1, CMD_DEFAULT, 0, 25, CommandType::all},
        {"stand", do_stand, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"switch", do_switch, position_t::RESTING, 0, CMD_DEFAULT, 0, 25, CommandType::all},
        {"tell", &Character::do_tell, position_t::RESTING, 0, CMD_TELL, 0, 1, CommandType::all},
        {"tellhistory", do_tellhistory, position_t::RESTING, 0, CMD_TELLH, 0, 1, CommandType::all},
        {"wield", do_wield, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"innate", do_innate, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"orchestrate", do_sing, position_t::RESTING, 0, CMD_ORCHESTRATE, 0, 0, CommandType::all},

        // Informational commands
        {"alias", &Character::do_alias, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::players_only},
        {"toggle", &Character::do_toggle, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"consider", do_consider, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"configure", &Character::do_config, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::players_only},
        {"credits", do_credits, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"equipment", do_equipment, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"ohelp", do_help, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"help", do_new_help, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"idea", do_idea, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"info", do_info, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"leaderboard", do_leaderboard, position_t::DEAD, 3, CMD_DEFAULT, 0, 1, CommandType::all},
        {"news", do_news, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"thenews", do_news, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"story", do_story, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"tick", do_tick, position_t::DEAD, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"time", do_time, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"title", do_title, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"typo", do_typo, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"weather", do_weather, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"who", &Character::do_who, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"wizlist", do_wizlist, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"socials", do_social, position_t::DEAD, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"index", do_index, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"areas", do_areas, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"commands", do_new_help, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"experience", &Character::do_experience, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::players_only},
        {"version", do_version, position_t::DEAD, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"identify", &Character::do_identify, position_t::DEAD, 0, CMD_DEFAULT, true, 0, CommandType::all},

        // Communication commands
        {"ask", do_ask, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"auction", &Character::do_auction, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"awaymsgs", do_awaymsgs, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::all},
        {"channel", do_channel, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"dream", do_dream, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"emote", do_emote, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {":", do_emote, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"gossip", do_gossip, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"trivia", do_trivia, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"gtell", do_grouptell, position_t::DEAD, 0, CMD_GTELL, 0, 1, CommandType::all},
        {".", do_grouptell, position_t::DEAD, 0, CMD_GTELL, 0, 1, CommandType::all},
        {"ignore", do_ignore, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"insult", do_insult, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"reply", do_reply, position_t::RESTING, 0, CMD_REPLY, 0, 1, CommandType::all},
        {"report", do_report, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"say", do_say, position_t::RESTING, 0, CMD_SAY, true, 0, CommandType::all},
        {"psay", do_psay, position_t::RESTING, 0, CMD_SAY, true, 0, CommandType::all},
        {"'", do_say, position_t::RESTING, 0, CMD_SAY, true, 0, CommandType::all},
        {"shout", do_shout, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"whisper", do_whisper, position_t::RESTING, 0, CMD_WHISPER, 0, 0, CommandType::all},

        // Object manipulation
        {"slip", do_slip, position_t::STANDING, 0, CMD_SLIP, 0, 1, CommandType::all},
        {"batter", do_batter, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"brace", do_brace, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"close", do_close, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"donate", do_donate, position_t::RESTING, 0, CMD_DONATE, true, 1, CommandType::all},
        {"drink", do_drink, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"drop", do_drop, position_t::RESTING, 0, CMD_DROP, true, 25, CommandType::all},
        {"eat", do_eat, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"fill", do_fill, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"give", do_give, position_t::RESTING, 0, CMD_GIVE, true, 25, CommandType::all},
        {"grab", do_grab, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"hold", do_grab, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"lock", do_lock, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"open", do_open, position_t::RESTING, 0, CMD_OPEN, true, 25, CommandType::all},
        {"pour", do_pour, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"put", do_put, position_t::RESTING, 0, CMD_PUT, true, 0, CommandType::all},
        {"quaff", do_quaff, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"read", do_read, position_t::RESTING, 0, CMD_READ, 0, 1, CommandType::all},
        {"remove", do_remove, position_t::RESTING, 0, CMD_REMOVE, true, 25, CommandType::all},
        {"erase", &Character::generic_command, position_t::RESTING, 0, CMD_ERASE, 0, 0, CommandType::all},
        {"sip", do_sip, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"track", &Character::do_track, position_t::STANDING, 0, CMD_TRACK, 0, 10, CommandType::all},
        {"take", do_get, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"palm", do_get, position_t::RESTING, 3, CMD_PALM, 0, 1, CommandType::all},
        {"sacrifice", do_sacrifice, position_t::RESTING, 0, CMD_SACRIFICE, true, 25, CommandType::all},
        {"taste", do_taste, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"unlock", do_unlock, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"use", do_use, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"wear", do_wear, position_t::RESTING, 0, CMD_DEFAULT, true, 25, CommandType::all},
        {"scribe", do_scribe, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"brew", do_brew, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        //  { "poisonmaking", do_poisonmaking, nullptr,nullptr, position_t::RESTING, 0, 9,   0, 0  ,CommandType::all},

        // Combat commands
        {"bash", do_bash, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"retreat", do_retreat, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"disarm", do_disarm, position_t::FIGHTING, 2, CMD_DEFAULT, 0, 0, CommandType::all},
        {"flee", do_flee, position_t::FIGHTING, 0, CMD_FLEE, true, 0, CommandType::all},
        {"escape", do_flee, position_t::FIGHTING, 0, CMD_ESCAPE, 0, 0, CommandType::all},
        {"hit", &Character::do_hit, position_t::FIGHTING, 0, CMD_HIT, true, 0, CommandType::all},
        {"join", &Character::do_join, position_t::FIGHTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"battlesense", do_battlesense, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"stance", do_defenders_stance, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"perseverance", do_perseverance, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"smite", do_smite, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},

        // Junk movedso join precedes it
        {"junk", do_sacrifice, position_t::RESTING, 0, CMD_SACRIFICE, true, 25, CommandType::all},

        {"murder", do_murder, position_t::FIGHTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"rescue", &Character::do_rescue, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"trip", do_trip, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"deathstroke", do_deathstroke, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"circle", do_circle, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"kick", do_kick, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"battlecry", do_battlecry, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"behead", do_behead, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"rage", &Character::do_rage, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"berserk", do_berserk, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"golemscore", do_golem_score, position_t::DEAD, 1, CMD_DEFAULT, 0, 1, CommandType::all},
        {"stun", do_stun, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"redirect", do_redirect, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"hitall", do_hitall, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"quiveringpalm", do_quivering_palm, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"eagleclaw", do_eagle_claw, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"headbutt", do_headbutt, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"cripple", do_cripple, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"fire", do_fire, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 25, CommandType::all},
        {"layhands", do_layhands, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"harmtouch", do_harmtouch, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"bloodfury", do_bloodfury, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"primalfury", do_primalfury, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"bladeshield", do_bladeshield, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"repelance", do_focused_repelance, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"vitalstrike", do_vitalstrike, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"crazedassault", do_crazedassault, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"bullrush", do_bullrush, position_t::STANDING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"ferocity", do_ferocity, position_t::STANDING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"tactics", do_tactics, position_t::STANDING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"deceit", do_deceit, position_t::STANDING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"knockback", do_knockback, position_t::FIGHTING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"appraise", do_appraise, position_t::STANDING, 1, CMD_DEFAULT, 0, 1, CommandType::all},
        {"make camp", do_make_camp, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"leadership", do_leadership, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"triage", do_triage, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"onslaught", do_onslaught, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"pursue", do_pursue, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},

        // Position commands
        {"sit", do_sit, position_t::RESTING, 0, CMD_DEFAULT, true, 0, CommandType::all},
        {"sleep", do_sleep, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"wake", &Character::do_wake, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 0, CommandType::all},

        // Miscellaneous commands
        {"editor", do_editor, position_t::SLEEPING, CMD_EDITOR, CMD_DEFAULT, 0, 1, CommandType::all},
        {"autojoin", do_autojoin, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"visible", do_visible, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"ctell", do_ctell, position_t::SLEEPING, 0, CMD_CTELL, 0, 1, CommandType::all},
        {"outcast", &Character::do_outcast, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"accept", do_accept, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"whoclan", do_whoclan, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"cpromote", do_cpromote, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"clans", do_clans, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"clanarea", &Character::do_clanarea, position_t::RESTING, 11, CMD_DEFAULT, 0, 1, CommandType::all},
        {"cinfo", do_cinfo, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"ambush", &Character::do_ambush, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"whoarena", do_whoarena, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"joinarena", do_joinarena, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"backstab", &Character::do_backstab, position_t::STANDING, 0, CMD_BACKSTAB, 0, 0, CommandType::all},
        {"bs", &Character::do_backstab, position_t::STANDING, 0, CMD_BACKSTAB, 0, 0, CommandType::all},
        {"sbs", &Character::do_backstab, position_t::STANDING, 0, CMD_SBS, 0, 0, CommandType::all}, // single backstab
        {"boss", do_boss, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"jab", do_jab, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"enter", do_enter, position_t::STANDING, 0, CMD_ENTER, true, 20, CommandType::all},
        {"climb", do_climb, position_t::STANDING, 0, CMD_CLIMB, true, 20, CommandType::all},
        {"examine", do_examine, position_t::RESTING, 0, CMD_EXAMINE, 0, 1, CommandType::all},
        {"follow", do_follow, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"stalk", do_stalk, position_t::STANDING, 6, CMD_DEFAULT, 0, 10, CommandType::all},
        {"group", do_group, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"found", do_found, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"disband", do_disband, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"abandon", do_abandon, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"consent", do_consent, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"whogroup", do_whogroup, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"forage", do_forage, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"whosolo", do_whosolo, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"count", do_count, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"hide", do_hide, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"leave", do_leave, position_t::STANDING, 0, CMD_LEAVE, true, 20, CommandType::all},
        {"name", do_name, position_t::DEAD, 1, CMD_DEFAULT, 0, 1, CommandType::all},
        {"pick", do_pick, position_t::STANDING, 0, CMD_PICK, 0, 20, CommandType::all},
        {"quest", do_quest, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"qui", do_qui, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"levels", do_levels, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"quit", do_quit, position_t::DEAD, 0, CMD_QUIT, 0, 1, CommandType::all},
        {"return", do_return, position_t::DEAD, 0, CMD_DEFAULT, true, 1, CommandType::all},
        {"tame", do_tame, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"free animal", do_free_animal, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"prompt", do_prompt, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"lastprompt", do_lastprompt, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"save", &Character::do_save, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"sneak", do_sneak, position_t::STANDING, 1, CMD_DEFAULT, 0, 0, CommandType::all},
        {"home", do_home, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"split", &Character::do_split, position_t::RESTING, 0, CMD_SPLIT, 0, 0, CommandType::all},
        {"spells", do_spells, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"skills", do_skills, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"songs", do_songs, position_t::SLEEPING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"steal", do_steal, position_t::STANDING, 1, CMD_DEFAULT, 0, 10, CommandType::all},
        {"pocket", do_pocket, position_t::STANDING, 1, CMD_DEFAULT, 0, 10, CommandType::all},
        {"motd", do_motd, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"cmotd", do_cmotd, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"cbalance", do_cbalance, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"cdeposit", &Character::do_cdeposit, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"cwithdraw", do_cwithdraw, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"ctax", do_ctax, position_t::STANDING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"where", do_where, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"write", do_write, position_t::STANDING, 0, CMD_WRITE, 0, 0, CommandType::all},
        {"beacon", do_beacon, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"beep", do_beep, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"guard", do_guard, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"release", do_release, position_t::STANDING, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        {"eyegouge", do_eyegouge, position_t::FIGHTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"vault", do_vault, position_t::DEAD, 10, CMD_DEFAULT, 0, 0, CommandType::all},
        {"suicide", do_suicide, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"vote", do_vote, position_t::RESTING, 0, CMD_VOTE, 0, 0, CommandType::all},
        {"huntitems", do_showhunt, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"random", do_random, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::all},
        {"arena", &Character::do_arena, position_t::DEAD, 0, CMD_DEFAULT, 0, 0, CommandType::players_only},
        {"search", &Character::do_search, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::players_only},
        {"vend", do_vend, position_t::STANDING, 2, CMD_VEND, 0, 0, CommandType::players_only},
        {"practice", do_practice, position_t::SLEEPING, 1, CMD_PRACTICE, 0, 0, CommandType::players_only},
        {"practise", do_practice, position_t::SLEEPING, 1, CMD_PRACTICE, 0, 0, CommandType::players_only},
        {"pray", do_pray, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::players_only},
        {"profession", do_profession, position_t::SLEEPING, 1, CMD_PROFESSION, 0, 0, CommandType::players_only},
        {"promote", do_promote, position_t::STANDING, 1, CMD_DEFAULT, 0, 0, CommandType::players_only},
        {"assemble", do_assemble, position_t::RESTING, 0, CMD_ASSEMBLE, 0, 0, CommandType::players_only},
        {"select", do_natural_selection, position_t::RESTING, 0, CMD_DEFAULT, 0, 0, CommandType::players_only},
        {"sector", do_sector, position_t::RESTING, 0, CMD_DEFAULT, 0, 1, CommandType::players_only},

        // Special procedure commands
        {"gag", &Character::generic_command, position_t::STANDING, 0, CMD_GAG, 0, 0, CommandType::players_only},
        {"design", &Character::generic_command, position_t::STANDING, 0, CMD_DESIGN, 0, 0, CommandType::players_only},
        {"stock", &Character::generic_command, position_t::STANDING, 0, CMD_STOCK, 0, 0, CommandType::players_only},
        {"buy", &Character::generic_command, position_t::STANDING, 0, CMD_BUY, 0, 0, CommandType::players_only},
        {"sell", &Character::generic_command, position_t::STANDING, 0, CMD_SELL, 0, 0, CommandType::players_only},
        {"value", &Character::generic_command, position_t::STANDING, 0, CMD_VALUE, 0, 0, CommandType::players_only},
        {"watch", &Character::generic_command, position_t::STANDING, 0, CMD_WATCH, 0, 0, CommandType::players_only},
        {"list", &Character::generic_command, position_t::STANDING, 0, CMD_LIST, 0, 0, CommandType::players_only},
        {"estimate", &Character::generic_command, position_t::STANDING, 0, CMD_ESTIMATE, 0, 0, CommandType::players_only},
        {"repair", &Character::generic_command, position_t::STANDING, 0, CMD_REPAIR, 0, 0, CommandType::players_only},
        {"price", &Character::generic_command, position_t::RESTING, 1, CMD_PRICE, 0, 0, CommandType::players_only},
        {"train", &Character::generic_command, position_t::RESTING, 1, CMD_TRAIN, 0, 0, CommandType::players_only},
        {"gain", &Character::generic_command, position_t::STANDING, 1, CMD_GAIN, 0, 0, CommandType::players_only},
        {"balance", &Character::generic_command, position_t::STANDING, 0, CMD_BALANCE, 0, 0, CommandType::players_only},
        {"deposit", &Character::generic_command, position_t::STANDING, 0, CMD_DEPOSIT, 0, 0, CommandType::players_only},
        {"withdraw", &Character::generic_command, position_t::STANDING, 0, CMD_WITHDRAW, 0, 0, CommandType::players_only},
        {"clean", &Character::generic_command, position_t::RESTING, 0, CMD_CLEAN, 0, 0, CommandType::players_only},
        {"play", &Character::generic_command, position_t::RESTING, 0, CMD_PLAY, 0, 0, CommandType::players_only},
        {"finish", &Character::generic_command, position_t::RESTING, 0, CMD_FINISH, 0, 0, CommandType::players_only},
        {"veternarian", &Character::generic_command, position_t::RESTING, 0, CMD_VETERNARIAN, 0, 0, CommandType::players_only},
        {"feed", &Character::generic_command, position_t::RESTING, 0, CMD_FEED, 0, 0, CommandType::players_only},
        {"pay", &Character::generic_command, position_t::STANDING, 0, CMD_PAY, 0, 0, CommandType::players_only},
        {"restring", &Character::generic_command, position_t::STANDING, 0, CMD_RESTRING, 0, 0, CommandType::players_only},
        {"push", &Character::generic_command, position_t::STANDING, 0, CMD_PUSH, 0, 0, CommandType::players_only},
        {"pull", &Character::generic_command, position_t::STANDING, 0, CMD_PULL, 0, 0, CommandType::players_only},
        {"gaze", &Character::generic_command, position_t::FIGHTING, 0, CMD_GAZE, 0, 0, CommandType::players_only},
        {"tremor", &Character::generic_command, position_t::FIGHTING, 0, CMD_TREMOR, 0, 0, CommandType::players_only},
        {"bet", &Character::generic_command, position_t::STANDING, 0, CMD_BET, 0, 0, CommandType::players_only},
        {"insurance", &Character::generic_command, position_t::STANDING, 0, CMD_INSURANCE, 0, 0, CommandType::players_only},
        {"double", &Character::generic_command, position_t::STANDING, 0, CMD_DOUBLE, 0, 0, CommandType::players_only},
        {"stay", &Character::generic_command, position_t::STANDING, 0, CMD_STAY, 0, 0, CommandType::players_only},
        {"remort", &Character::generic_command, position_t::RESTING, GIFTED_COMMAND, CMD_REMORT, 0, 1, CommandType::players_only},
        {"reroll", &Character::generic_command, position_t::RESTING, 0, CMD_REROLL, 0, 0, CommandType::players_only},
        {"choose", &Character::generic_command, position_t::RESTING, 0, CMD_CHOOSE, 0, 0, CommandType::players_only},
        {"confirm", &Character::generic_command, position_t::RESTING, 0, CMD_CONFIRM, 0, 0, CommandType::players_only},
        {"cancel", &Character::generic_command, position_t::RESTING, 0, CMD_CANCEL, 0, 0, CommandType::players_only},

        // Immortal commands
        {"voteset", do_setvote, position_t::DEAD, 108, CMD_SETVOTE, 0, 1, CommandType::immortals_only},
        {"thunder", do_thunder, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"wizlock", do_wizlock, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"processes", do_processes, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"bestow", &Character::do_bestow, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"oclone", do_oclone, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"mclone", do_mclone, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"huntclear", do_huntclear, position_t::DEAD, 105, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"areastats", do_areastats, position_t::DEAD, 105, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"huntstart", do_huntstart, position_t::DEAD, 105, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"revoke", do_revoke, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"chpwd", do_chpwd, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"advance", do_advance, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"skillmax", do_maxes, position_t::DEAD, 105, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"damage", do_dmg_eq, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"affclear", do_clearaff, position_t::DEAD, 104, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"guide", &Character::do_guide, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"addnews", do_addnews, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"linkload", &Character::do_linkload, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"listproc", do_listproc, position_t::DEAD, OVERSEER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"zap", &Character::do_zap, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"slay", do_slay, position_t::DEAD, OVERSEER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"rename", &Character::do_rename_char, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"archive", do_archive, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"unarchive", do_unarchive, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"stealth", do_stealth, position_t::DEAD, OVERSEER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"disconnect", do_disconnect, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"force", do_force, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"pardon", do_pardon, position_t::DEAD, OVERSEER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"goto", &Character::do_goto, position_t::DEAD, 102, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"restore", do_restore, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"purloin", do_purloin, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"set", do_set, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"unban", do_unban, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"ban", do_ban, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"echo", do_echo, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"eqmax", do_eqmax, position_t::DEAD, 105, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"send", do_send, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"at", do_at, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"fakelog", do_fakelog, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"global", do_global, position_t::DEAD, 108, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"log", do_log, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"snoop", &Character::do_snoop, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"pview", do_pview, position_t::DEAD, 104, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"load", do_load, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"prize", do_load, position_t::DEAD, GIFTED_COMMAND, CMD_PRIZE, 0, 1, CommandType::immortals_only},
        {"test", &Character::do_test, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"testport", do_testport, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"testuser", do_testuser, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"shutdow", &Character::do_shutdow, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"shutdown", &Character::do_shutdown, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"opedit", do_opedit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"opstat", do_opstat, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"procedit", do_procedit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"procstat", do_mpstat, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"range", do_range, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        // { "pshopedit",	do_pshopedit,	position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1  ,CommandType::immortals_only},
        {"sedit", do_sedit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"sockets", &Character::do_sockets, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"punish", do_punish, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"sqedit", do_sqedit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"qedit", do_qedit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"install", do_install, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        //  { "motdload",       do_motdload,    position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1  ,CommandType::immortals_only},
        {"hedit", do_hedit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"hindex", do_hindex, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"reload", do_reload, position_t::DEAD, OVERSEER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"plats", do_plats, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"bellow", do_thunder, position_t::DEAD, DEITY, CMD_BELLOW, 0, 1, CommandType::immortals_only},
        {"string", do_string, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"transfer", do_transfer, position_t::DEAD, DEITY, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"gtrans", do_gtrans, position_t::DEAD, DEITY, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"boot", do_boot, position_t::DEAD, DEITY, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"linkdead", do_linkdead, position_t::DEAD, DEITY, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"teleport", do_teleport, position_t::DEAD, DEITY, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"purge", do_purge, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"show", do_show, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"fighting", do_fighting, position_t::DEAD, 104, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"peace", do_peace, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"check", do_check, position_t::DEAD, 105, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"zoneexits", do_zoneexits, position_t::DEAD, 104, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"find", do_find, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"stat", do_stat, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"redit", do_redit, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"guild", do_guild, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"oedit", do_oedit, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"clear", do_clear, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"repop", do_repop, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"medit", do_medit, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"rdelete", do_rdelete, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"oneway", do_oneway, position_t::DEAD, ANGEL, 1, 0, 1, CommandType::immortals_only},
        {"twoway", do_oneway, position_t::DEAD, ANGEL, 2, 0, 1, CommandType::immortals_only},
        {"zsave", &Character::do_zsave, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"rsave", do_rsave, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"msave", do_msave, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"osave", do_osave, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"rstat", do_rstat, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"possess", do_possess, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"fsave", do_fsave, position_t::DEAD, 104, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"zedit", do_zedit, position_t::DEAD, ANGEL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"colors", do_colors, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"colours", do_colors, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"incognito", do_incognito, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"high5", do_highfive, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"holylite", do_holylite, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"immort", do_wiz, position_t::DEAD, IMMORTAL, CMD_IMMORT, 0, 1, CommandType::immortals_only},
        {";", do_wiz, position_t::DEAD, IMMORTAL, CMD_IMMORT, 0, 1, CommandType::immortals_only},
        {"impchan", do_wiz, position_t::DEAD, GIFTED_COMMAND, CMD_IMPCHAN, 0, 1, CommandType::immortals_only},
        {"/", do_wiz, position_t::DEAD, GIFTED_COMMAND, CMD_IMPCHAN, 0, 1, CommandType::immortals_only},
        {"nohassle", do_nohassle, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"wizinvis", do_wizinvis, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"poof", do_poof, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"wizhelp", &Character::do_wizhelp, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"imotd", do_imotd, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"mhelp", do_mortal_help, position_t::DEAD, IMMORTAL, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"testhand", do_testhand, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"varstat", do_varstat, position_t::DEAD, 104, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"matrixinfo", do_matrixinfo, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"maxcheck", do_findfix, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"export", do_export, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"mscore", do_mscore, position_t::DEAD, 103, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"world", do_world, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},

        // Special procedure commands placed to not disrupt god commands
        {"setup", do_mortal_set, position_t::STANDING, 0, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"metastat", do_metastat, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"testhit", do_testhit, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"acfinder", do_acfinder, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"findpath", do_findPath, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"findpath2", do_findpath, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"addroom", do_addRoom, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"newpath", do_newPath, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"listpathsbyzone", do_listPathsByZone, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"listallpaths", do_listAllPaths, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"dopathpath", do_pathpath, position_t::DEAD, GIFTED_COMMAND, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"botcheck", &Character::do_botcheck, position_t::DEAD, 106, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"showbits", do_showbits, position_t::DEAD, OVERSEER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},
        {"debug", do_debug, position_t::DEAD, IMPLEMENTER, CMD_DEFAULT, 0, 1, CommandType::immortals_only},

        // Bug way down here after 'buy'
        {"bug", do_bug, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::all},
        // imbue after 'im' for us lazy immortal types :)
        {"imbue", do_imbue, position_t::STANDING, 0, CMD_DEFAULT, 0, 0, CommandType::all},

        // MOBprogram commands
        {"mpasound", do_mpasound, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpbestow", do_mpbestow, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpjunk", do_mpjunk, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpecho", do_mpecho, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpechoat", do_mpechoat, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpechoaround", do_mpechoaround, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpechoaroundnotbad", do_mpechoaroundnotbad, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpkill", do_mpkill, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mphit", do_mphit, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpaddlag", do_mpaddlag, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpmload", do_mpmload, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpoload", do_mpoload, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mppurge", do_mppurge, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpgoto", do_mpgoto, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpat", do_mpat, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mptransfer", do_mptransfer, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpthrow", do_mpthrow, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpforce", do_mpforce, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mppeace", do_mppeace, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpsetalign", do_mpsetalign, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpsettemp", &Character::do_mpsettemp, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpxpreward", do_mpxpreward, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpteachskill", do_mpteachskill, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpdamage", do_mpdamage, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpothrow", do_mpothrow, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mppause", do_mppause, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpretval", do_mpretval, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpsetmath", do_mpsetmath, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},
        {"mpteleport", do_mpteleport, position_t::DEAD, 0, CMD_DEFAULT, 0, 1, CommandType::non_players_only},

        // End of the line
        {"", &Character::generic_command, position_t::DEAD, 0, CMD_DEFAULT, true, 0}};

auto Commands::find(QString arg) -> std::expected<Command, search_error>
{
    if (map_.contains(arg))
    {
        return map_.value(arg);
    }

    return std::unexpected(search_error::not_found);
}

Commands::Commands(void)
{
    for (const auto &command : commands_)
    {
        map_[command.getName()] = command;
        for (qsizetype position = 1; position < command.getName().length(); position++)
        {
            auto keyword = command.getName();
            keyword.truncate(position);
            if (!map_.contains(keyword))
            {
                map_[keyword] = command;
            }
        }
    }
}
