import glob

env = Environment()
env.Append(CCFLAGS = '-O -g3 -Wall -Wno-write-strings -m32')
env.Append(LINKFLAGS = '-O -g3 -Wall -Wno-write-strings -m32')

base_src = glob.glob('*.cpp')
wizard_src = glob.glob('wizard/*.cpp')
class_src = glob.glob('class/*.cpp')
backend_src = glob.glob('Backend/*.cpp')

env.Program('research.debug', [base_src,wizard_src,class_src,backend_src],
CPPPATH = ['include','/usr/include/pgsql/'], CPPDEFINES=['LINUX'],
LIBS=['crypt', 'mcheck', 'z', 'pq', 'xmlrpc++'], LIBPATH=['/emul/linux/x86/lib', '/usr/local/lib32']);
