import glob

env = Environment()
env.Append(CCFLAGS = '-ggdb3 -Wall -m32 -O3 -Wno-write-strings')
env.Append(LINKFLAGS = '-ggdb3 -Wall -m32 -O3 -Wno-write-strings' )

base_src = glob.glob('[a-l]*.cpp') + glob.glob('[n-z]*.cpp') + glob.glob('mo*.cpp') + ['magic.cpp','memory.cpp','meta.cpp','MobActivity.cpp']
wizard_src = glob.glob('wizard/*.cpp')
class_src = glob.glob('class/*.cpp')
backend_src = glob.glob('Backend/*.cpp')

env.Program('dcastle.debug', ['main.cpp'],
CPPPATH = ['include'], CPPDEFINES=['LINUX'],
LIBS=['dcastle','crypt', 'mcheck', 'z', 'pq', 'xmlrpc++'], LIBPATH=['.','/usr/local/lib']);

env.Program('showplayer', ['../scripts/showplayerxp.cpp'],
CPPPATH = ['include'], CPPDEFINES=['LINUX'],
LIBS=['dcastle','crypt', 'mcheck', 'z', 'pq', 'xmlrpc++'], LIBPATH=['.','/usr/local/lib']);

env.StaticLibrary('dcastle', [base_src,wizard_src,class_src,backend_src],
CPPPATH = ['include','/usr/include/pgsql/'], CPPDEFINES=['LINUX'],
LIBS=[], LIBPATH=['/usr/local/lib']);